---
title: "シダ植物を追いかけて：シダ植物の進化生物学的研究"
bibliography: references.yaml
crossref: 
  fig-title: Fig.
  tbl-title: Table
  fig-prefix: Fig.
  tbl-prefix: Table
format: docx
---

ニッタ ジョエル

生物学的研究においては、古くからモデル生物やモデルシステムの使用が広く行われてきたアプローチである。
なぜなら、一人の研究者が全ての生物を全てのレベルで研究することが不可能だからである。その代わりに、特定の系統や種に焦点を当てて深く探求することによって、そのモデル生物の性質だけでなく、生物学における一般的な現象やメカニズムを発見することができる。最もよく知られている植物のモデル生物は主に遺伝子の役割などを解明するために利用されてきたシロイヌナズナだが、筆者は進化生物のモデルシステムとしてシダ植物に着目して、シダ植物に関連する様々生態・進化的な現象を調べてきた。本論文では、普段論文にあまり言及しない研究の背景に触れながら、これまでの研究を紹介したいと思う。

## 総合的分類学アプローチ

筆者の研究対象としてのシダ植物との出会いは2006年に受けたカリフォルニア大学バークレー校の野外実習だった。この実習は大学部生の授業では珍しく、学期の多くを大学が持っているフランス領ポリネシアのモーレア島にある研究所に過ごし、現地でその島の生物にまつわるテーマを自ら選び、仮説をたて、検証し、論文を書く課題となっている。その当時の先生のBrent Mishler教授にコケシノブ科シダ植物を研究材料としてお勧めいただき、比較的にシダ植物の少ないカリフォルニア出身の筆者にとっては初めて見るこの半透明ほど薄い葉っぱを持つ不思議な植物が非常に面白かった。そこで、授業の課題だけでなく、そのあとさらにMishler先生の研究室でシダ植物の大先輩であるAlan Smith博士に教わりながらDNA解析を行い、卒業論文としてモーレア島のコケシノブ調査を発表した[@Nitta2008]。本論文では、DNAバーコードに基づき分類学的な混乱があった分類群を整理し、さらに系統分類上で分子データのみでなく、形態的特徴や生育環境なども考慮した総合的分類学アプローチの重要性を議論した。この総合的分類学アプローチは後の筆者の研究においても重要なテーマになった。そして、学部の卒業後、大学院に進学する前に、コスタリカでOrganization for Tropical Studies (OTS)が提供している「Specialty Course on Tropical Ferns and Lycophytes」に参加することが出来、Robbin Moran主幹、James ("Eddie") Watkins教授、Kathleen Pryer教授、Donald Farrar名誉教授など有名なシダ植物の先生に集中的に熱帯シダ植物について教わっていただく機会によってさらにシダ植物へ対する興味を深めた。

コケシノブの研究を続けるために、次にコケシノブの分類体系を大きく改善した[@Ebihara2006]国立科学博物館の海老原淳主幹に連絡して見たが、彼のお勧めで大学院生の受け入れが出来る東京大学の伊藤元己教授の研究室に入った。筆者は学部で生物学と日本語を複数専攻にし、日本で生活をしたかったので、日本の大学でシダ植物の研究が出来ることはとても嬉しかった。修士論文の研究テーマはウチワゴケ近縁種群における網状進化だった[@Nitta2011]。

系統分類学は、過去に起こっと進化的な事実を人間が使えるシステムに纏まる試みである。種と種との境目が明らかで、一旦分かれた系統が他の系統と合流しない限り、この試みはさほど難しいことはない。しかし、シダ植物は雑種形成や無配生殖（クローン増殖）といったプロセスが頻繁に起こり、この作業を極めて困難にする[@Barrington1989]。そこで必要になって来るのは、複数のマーカー（DNA領域）による系統解析である。シダ植物は他の多くの植物と同様に、葉緑体は片方の親（シダ植物では母親）からしか引き継がれないのに対して、核は両方の親から引き継がれる[@Gastony1992; @Vogel1998]。よって、雑種の場合では、葉緑体は一コピーのみのに対して、核マーカーは二つ以上になる（高次倍数体の場合は三つ以上もあり得る）。なので、雑種形成が起こった可能性があるグループでは、葉緑体マーカーと核マーカーの組み合わせで解析する必要がある[@Grusz2009]。

ウチワゴケ近縁種群（*Crepidomanes minutum*）を研究材料に選んだ理由は、連続的な形態的な変異に伴う分類学的混乱を整理する必要があったからである[@Copeland1958]。さらに、高次倍数体や無配生殖[@Braithwaite1969; @Braithwaite1975]の報告があったので網状進化があったと思われたのが、その当時までは系統解析が行われてこなかったので確かめる必要があった。@Nitta2011 では、葉緑体マーカーと核マーカーを一つずつ系統解析に用いることによって、本グループの進化的な歴史を明らかにすることができた。まず、本グループにおいては分布や形が異なる二つの大きなクレードが存在していることが分かった。次に、片方の主に東南アジアに分布してるクレード内に雑種が頻繁に形成されることに対して、日本の物を含むもう片方は比較的に雑種形成が少ないことが分かった。面白いことに、一個体だけ二つのクレードの両方からシーケンスを持つ株が観察できたのだが、この株は２倍体の有性の物だったことから、雑種形成ではなく、シダ植物において報告の珍しいancient lineage sortingによる組み合わせであることが示唆された。おそらく二つのクレードの中にそれぞれ複数の二倍体種とその間の雑種が存在していると思われるが、旧政界に広く分布している本近縁種群の分類体系を見直すのにこの研究ではまだサンプリングが足りず、今後の課題としてまだ残されている。

## 隠蔽ライフステージの役割解明

シダ植物の最も興味深い特徴の一つはその独特なライフサイクルである。種子植物や苔植物など、他の陸上植物と同様に、シダ植物には二倍体の胞子体と一倍体の配偶体という二つのライフステージを持つが、この二つがそれぞれ独立に生育できるのはシダ植物だけである。通常、「シダ植物」として認識されているのは大きな方の胞子体だが、配偶体が有性生殖を担っている（つまり、卵子と精子を形成している）ため、むしろ大事な方だと言える。配偶体はとても小さい（多くのものは1センチ以下）、そして多くのものは形態だけで種同定が出来ないほど形態的にシンプルであるため、長い間シダ植物研究者の視野には入って来なかったが、この状況は最近やっと変わりつつある。近年はDNAバーコード法によって野外で採集された配偶体の的確な種同定が可能になったので、やっと配偶体の生態的な役割を種レベルで探ることが出来るようになった。

ハーバード大学のCharles Davis教授の元で博士課程に入った筆者は、DNAバーコードにより野外で採取したシダ植物配偶体の種同定を行い、当時までわかっていなかったシダ植物にまつわる現象をいくつか解明することにした[@Nitta2017; @Nitta2018; @Nitta2020; @Nitta2021]。ちょうどその時、学部生だったカリフォルニア大学バークレー校では、モーレア島の全生物調査が行われいていて、筆者は博士に進学する前からシダ植物部門を担当していたので、島のシダ植物（やく１４０種）は既にDNAデータ（葉緑体rbcLとtrnH-psbA）がほぼ揃っていたので、配偶体のDNAバーコードを行うのに好条件だった[@Nitta2011b]。そこで、３回ほどモーレア島に渡り、島全体の胞子体・配偶体の調査を行なった 。なぜ改めて胞子体を採取するかというと、今度は胞子体と配偶体の群集構造を比較するのが一つの目的だったからである。標高勾配に沿って、約200メートルから1200メートルまで、さらにより標高の高いサンプルを得るために隣のタヒチ島で600mから2000m計25調査地を設置して、胞子体と配偶体を両方とも観察し、配偶体をDNAバーコードで種同定を行なった[@Nitta2017]。

結果として、予想通りに胞子体と配偶体が違う分布パターンを示すことが分かった[@Nitta2017]。胞子体の群集構造は標高と密接な関係を示すのに対し、配偶体の群集構造は標高と有意義な関係が見られなかった。これは胞子体の方が配偶体よりも環境に強く影響されることを示唆し、先行研究[@Sato1981; @WatkinsJr.2007c]でも配偶体の方が胞子体より厳しい（例えば、乾燥している）環境を耐えることが出来ることと一致する結果となった。しかし、コケシノブで胞子体と配偶体の乾燥耐性を試して見たら、逆に配偶体が弱いこともあるという意外な結果が得られた[@Nitta2021]。野外でよく観察すると、配偶体で最も広い分布している*Callistopteris apiifolia*の配偶体はそもそも乾燥しにくいマイクロハビタット（期の幹の基部のちょっとした窪みなど）に特異的に生育することが多いことが分かった（面白いことに、同種は西表島や他の南方の島でも同じよう配偶体だけで広く分布していことが知られている;米岡pers. comm.、@Dassler1997)。さらに、単独ではなく、複数の個体がクローン増殖によってマットを形成し、マットの内部を乾燥から守っていると思われる。つまり、シダ植物の配偶体は複数の戦略（乾燥耐性、マイクロビタットの利用）によって生き残っていることが示唆された。同時期の研究においてこの他に、ウラボシ属の新雑種[@Nitta2018]や着生シダ植物の形態的特徴がその当時まで思っていたよりも多様であるという発見があった[@Nitta2018]。

## 生物多様性の地図上可視化

群集生態学に興味を持ち始めた筆者は、さらに大きなスケールでシダ植物の多様性解析をしてみたいと思った。ポスドック研究では国立科学博物館の海老原淳先生の研究室に入り、その時はちょうど先生が日本のシダ植物のデータセットを再評価していたので、ある地域全体においてのシダ植物多様性解析をするのにちょうど良い材料だった。

長い間、生物多様性の評価は種数だけが用いられたが、これは進化的な歴史を無視するので、どうしてもこの手法から得られる理解が限られている。その代わりに系統樹の枝の長さを使えば、進化的な多様性の計測が可能になり、ある地域の進化や生物地理を理解するには勿論、保全活動にも重要な参考となる。これはいわゆるPD[Phylogenetic diversity; @Faith1992]の手法である。PD自体はさほど新しくないが、多くの種を入れた系統樹というPDを測るために必須なデータが最近までなかったため、広く使われなこなかった。しかし、ちょうど筆者が研究をし始めた頃（２０１０年代）から、DNAデータとそれを生み出す技術が著しく早い速度で発展を成し遂げ、あらゆる分類群においてPDの解析が可能になってきた。そして、これに伴って生物多様性解析の面でも新しい展開があった。特に、PDと同じように系統樹の枝の長さを利用したPhylogenetic endemism[PE; 系統的固有性; @Rosauer2009]やPEを古い過程によるもの（paleo-endemism；古代固有性）と最近の過程によるもの（neo-endemism）に分類する方法であるCANAPE[Categorical Analysis of Neo- and Paleo-endemism; @Mishler2014]によって、初めて地図上で生物多様性を生み出す過程の可視化が可能になった。

このような解析を行うには系統樹だけでなく、高解像度な分布データも必要である。DNAデータが最近かなり増えてきたにもかかわらず、ある地域においてDNAデータと分布データが両方とも高解像度に揃っているケースは少ないが、日本のシダ植物は珍しく両方とも揃っている。なぜかと言うと、日本はその面積の割にシダ植物の研究が随分前から活発に行われてきて、今でも日本シダの会など一般の方と研究者が一緒になって常に日本のシダ植物の観察を続けてきたからである。このデータを集計して、やく10km x 10 kmの解像度で日本産シダ植物のほぼ全種類を含む地図を作成し、再評価した[@Ebihara2019b]。さらに、葉緑体遺伝子rbcLによる系統樹と組み合わせ、全国においてCANAPE解析を含む系統固有性を解析した。その結果、日本では特に南北（琉球列島と北海道）に系統が古い物が密集していること、そして琉球に系統固有性が非常に高いことが分かった。これは亜熱帯の気候を持つ琉球に本州に入り込めない熱湯的な系統が数多く生育していることによると思われる。さらに、保全地域や食害で問題となっている日本ジカの分布と比べることによって、日本シダ植物の生物多様性がどのように保全されている、そして食害の危機にさらされているのか、解析した。その結果、系統固有性の高いエリアは比較的によく守られている（平均よりも保護区に入っている面積が多い）のに対して、種数が高いエリア（特に四国と九州に密集している）が日本ジカの分布とかなり重なっている、つまり、食害に晒されていることが分かった。これは保全政策において、生物多様性の評価を複数の方法で測る必要があることを示唆する。

## シダ植物のデータサイエンス

日本シダ植物の生物多様性において行ったCANAPE解析はその当時BiodiverseというGUI（グラフィカルユーザインタフェース）のソフトでしか出来ない状態だった。筆者は大学院生の終わり頃からSoftware Carpentryというアメリカ発の研究者がお互いに教え合うワークショップに参加することによって、データサイエンスについて学び、その時から可能な限り（将来の自分を含めて）他の研究者が自分のデータ解析の再現が出来るように努力している。データ解析を可能にするツールは様々あるが、基本的にはプログラミング、データとスクリプトのオープンアクセス化、計算環境の管理と大きく三つのカテゴリーに分けられる。CANAPE解析をRプログラミング言語で出来るようにしようと思い、新しいRパッケージ「canaper」を作成した（Nitta et al 2023）。こうすることによって、その時までBiodiverseで様々なメニューを目で追ってクリックする（つまり、他の研究者に再現するのが難しい状況）のではなく、全ての解析の段階をスクリプトとして保存するこによってCANAPE解析の再現を大幅にやり易くした。さらに、並列計算の機能もパッケージに入れることによって、解析の効率を大幅に高めることが出きた。

このようにデータサイエンスを身に付けた筆者はシダ植物の系統樹にも応用しようと思った。@Hasebe1994 を始め、その当時の「全シダ植物系統樹」を作る試みが今まで数回あった[@Schuettpelz2007; @Lehtonen2011; @Testo2016a]。しかし、全シダ植物系統樹を作るのはもちろん簡単な作業ではないので、５−７年くらいのペースで論文が出ていた。その間に新しいデータがどんどん「GenBank」というデータベースに蓄積されているにも関わらず、新しい系統樹が発表されないので、最新の系統樹を使いたかったら、自分で一から作るか、待つのかというどちろも好ましくない選択肢しかなかった。そこで、筆者はデータサイエンスのツール（つまり、プログラミングや計算環境の管理など）を使うことによって、常に最新状態を保つ全シダ植物系統樹作成システムを作るこにした。スミソニアン博物館でのポスドックのアドバイザーだったEric Schuettpelz主幹と特任助教を務めた東京大学の岩崎渉先生と共同研究でこのシステムを作成し、発表した[@Nitta2022b]。このシステムによる「最も多きな」系統樹はその時まで最も大きな系統樹より種数が約４０％増えて、いくつかその時まではっきりしていなかった深い分岐点を明らかにすることが出きた[@Nitta2022b]。しかし、この結果よりむしろ重要だと筆者が思うのは、この系統樹を誰でも簡単に使えるようにポータルサイト（https://fernphy.github.io/）とRパッケージ（https://github.com/joelnitta/ftolr）の提供、そして定的（GenBankのアップデートに紐付け、年に４回ほど）にこの系統樹を更新することである。こうすることによって、系統解析は一回の論文として終わるのではなく、今後ともシダ植物に関する様々研究に役立つことを強く望んでいてる。

データサイエンスや再現可能なデータ解析のツールを研究しながら身に付けた筆者は自分の経験から、他の研究者にも是非このツールが使えるようになって欲しいと思い、まだ日本であまり普及していないSoftware Carpentryとその親組織のThe Carpentriesを広めるように務めている[@Wilson2016]。多くの場合、研究者は大変な思いをしながら独学で研究に必要な解析ツールを学ぶのだが、必ずしもそうである必要はない。コミュニティーとなって、お互いにベストプラクティスを教え合うことによって、効率よく、楽しく出来るということはThe Carpentriesの活動を通じて筆者が分かった。具体的には、研究施設でThe Carpentriesが無料で提供している教材を使って、数日に渡るワークショップを教える・受けることによって、最新ツールの基本的な使い方と概念を身に着けて、自分の研究を加速させるだけでなく、他の研究者との繋がりも作って、研究生活をより楽しく過ごすことに繋がる。

## 終わりに

「なぜシダ植物（を研究する）？」をよく聞かれる。理論的な理由はいくつかある：陸上植物の中で胞子体と配偶体がそれぞれ独立に生育できるのはシダ植物だけであるとか、種子植物の姉妹群として系統的に非常に大事であるとか。しかし、私にとって最も大きな理由は、個人的に非常に強く惹かれているからである。シダ植物を自然の中で観察して、その進化や生態学に色々と思いを巡らせることがなんと言っても楽しい、面白い。こんなに長く、様々な面から自分の好きな物を研究することが出きたことはとてもラッキーだと思う。そして、このように自分の思いついたアイディアを自由に追求させてくれた指導教員に深く感謝している。長く研究活動を続けられるのに、飽きない好奇心とそれを追って行く根性が必要だと思われる。指導していただいた先生建や共同研究者にいつも応援していただいたお蔭様でここまで来れたと思う。この場をお借りして、御礼を申し上げる：Brent Mishler、Alan R. Smith、James "Eddie" Watkins Jr., Kathleen Pryer, Donald Farrar, Robbin Moran, 海老原淳、伊藤元己、
